# Use root/example as user/password credentials
services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - mongo-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    networks:
      - mongo-network
    depends_on:
      - mongo

  express:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
      - EXPRESS_DATABASE_TYPE=mongodb
      - EXPRESS_DATABASE_HOST=mongo
      - EXPRESS_DATABASE_PORT_NUMBER=27017
      - DATABASE_URL=mongodb://root:example@mongo:27017
      - EXPRESS_SKIP_DB_WAIT=0
      - EXPRESS_SKIP_DB_MIGRATION=0
      - EXPRESS_SKIP_NPM_INSTALL=0
      - EXPRESS_SKIP_BOWER_INSTALL=0
    volumes:
      - './app:/app'
    networks:
      - mongo-network
    depends_on:
      - mongo




networks:
  mongo-network:
    driver: bridge

